Repository labstack/echo, pull requests merged in 2021-01, with the labels that each got.

#1741 Do not handle special trailing slash case for partial prefix
  router.go
  router_test.go
Labels: bug, unconfirmed

#1734 issue #1729 - Binding query/path params and form fields to struct only works for explicit tags
  bind.go
  bind_test.go
Labels: discussion

#1743 Timeout middleware implementation
  middleware/timeout.go
  middleware/timeout_test.go
Labels: discussion, enhancement, middleware

#1724 adds middleware for rate limiting
  .gitignore
  go.mod
  go.sum
  middleware/rate_limiter.go
  middleware/rate_limiter_test.go
Labels: discussion, enhancement
